# see https://symfony.com/doc/current/reference/configuration/framework.html
parameters:
    env(SESSION_TTL): '604800'

framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: true

    # Note that the session will be started ONLY if you read or write from it.
    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        cookie_secure: auto
        cookie_samesite: lax
        cookie_lifetime: '%env(int:SESSION_TTL)%'
        storage_factory_id: session.storage.factory.native
        gc_maxlifetime: '%env(int:SESSION_TTL)%'

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            handler_id: session.handler.native_file
            storage_factory_id: session.storage.factory.mock_file
